export const SIGNUP = '/auth';
export const LOGIN = '/auth/sign_in';
export const FORGOT_PASS = '/auth/password';
export const OTP_VERIFY = '/users/verify_otp';
export const NEW_PASS = '/auth/password';
export const GLOBAL_CATEGORIES = '/customers/global_categories';
export const SEARCH_BY_NAME = "/customers/photographer_by_name?search=";
export const SEARCH_BY_CATEGORY = "/customers/photographer_by_category?search[]=";
export const SEARCH_BY_LOCATION = "/customers/search_photographer?start_date=";
export const FETCH_PHOTOGRAPHER_BY_ID = "/photographers/";
export const FETCH_PHOTOGRAPHER_WORK_BY_ID ="/photographers/work_list?photographer_id=";
export const FETCH_PHOTOGRAPHER_WORK_CATEGORY ="/photographers/categories?photographer_id=";
export const SHOW_PACKAGE = "/packages?photographer_id=";
export const GET_PACKAGE = "/packages/";
export const ADD_CATEGORY = "/photographers/add_categories";
export const CREATE_PROFILE = "/photographers/create_profile";
export const ME = '/users/me';
export const UPLOAD_WORK = "/photographers/upload_work";
export const CREATE_PACKAGE = "/packages";
export const DEL_PACKAGE = "/packages/";
export const EDIT_PACKAGE = "/packages/";
export const EDIT_PROFILE = "/users/";